public class CSVFileCreator {
/*    public static void createCSVFile(String csvContent) {
        Blob csvBlob = Blob.valueOf(csvContent);

        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = 'MyCSVFile.csv';
        contentVersion.PathOnClient = 'MyCSVFile.csv';
        contentVersion.VersionData = csvBlob;
        contentVersion.Origin = 'H';

        insert contentVersion;
        system.debug();
    }*/

}